import { Bar } from "@/components/Dashboard/Bar";
import { SideBar } from "../components/SideBar";
import "./globals.css";
import { Roboto } from "next/font/google";
import styles from "./page.module.css";

const roboto = Roboto({
  weight: ["400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Bar />

        {children}
      </body>
    </html>
  );
}
